#!/bin/sh
set -e

PACKAGE=
[ "$PACKAGE" ]

if [ "$1" = "configure" -a -x /usr/lib/emacsen-common/emacs-package-install ]
then
        /usr/lib/emacsen-common/emacs-package-install "$PACKAGE"
fi

if [ "$1" = "configure" ]; then
        if [ -d /usr/doc -a -h /usr/doc/$PACKAGE -a -d /usr/share/doc/$PACKAGE ]; then
                rm -f /usr/doc/$PACKAGE 
        fi
fi

#DEBHELPER#

