#!/bin/sh
set -e

PACKAGE=
[ "$PACKAGE" ]

if [ -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
        /usr/lib/emacsen-common/emacs-package-remove "$PACKAGE"
fi

if [ \( "$1" = "upgrade" -o "$1" = "remove" \) \
    -a -L /usr/doc/$PACKAGE ]; then
        rm -f /usr/doc/$PACKAGE
fi
